In [3]:
import numpy as np
print(np.__version__)

2.0.2


In [4]:
#for list of numbers
import numpy as np
my_list= [1,2,3,4]
my_list= my_list*2 #returns the list duplicate
print(my_list)

[1, 2, 3, 4, 1, 2, 3, 4]


In [6]:
#for a numpy array
import numpy as np
array= np.array([1,2,3,4])
print(array)
print(type(array))
array= array*2 # returns element times 2
print(array)

[1 2 3 4]
<class 'numpy.ndarray'>
[2 4 6 8]


In [7]:
#MULTIDIMENSIONAL ARRAYS

In [20]:
import numpy as np
array= np.array('A')
print(array.ndim) #gives the no of dimensions(ndim)
array=np.array(['A','B','C'])
print(array.ndim)
array=np.array([['A','B','C'],
                ['D','E','F'],
                ['G','H','I']])
print(array.ndim)
print(array.shape) #it will give us the no of tuples or layers, since its a 2D array it will give only length and breadth each having 3 elements in each
array= np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
                 [['J','K','L'],['M','N','O'],['P','Q','R']],
                 [['J','K','L'],['M','N','O'],['P','Q','R']]])
#chain indexing
print(array[0][0][0]) # array indexing, returns A(chain indexing)
#multidimensional indexing
print(array[0,0,0])
# Making a word using multidimensional indexing
array= np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
                 [['J','K','L'],['M','N','O'],['P','Q','R']],
                 [['J','K','L'],['M','N','O'],['P','Q','R']]])
word = array[0,0,0]+array[0,1,0]+array[0,1,0]+array[1,1,2]+array[2,1,1]
print(word)

0
1
2
(3, 3)
A
A
ADDON


In [21]:
# SLICING using numpy

In [34]:
import numpy as np
array= np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]])
# array[start:end:step]- for slicing
print(array[0:4:2]) # row selection
print(array[:,0]) # returning single column
print(array[:,0:3]) # first 3 columns
print(array[:,1:4]) # returning remaining columns except the first column
print(array[:,::2]) # selecting every row and column by setting the step
print(array[0:2, 0:2]) # selecting elements in first 2 rows and first 2 columns

[[ 1  2  3  4]
 [ 9 10 11 12]]
[ 1  5  9 13]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]
[[1 2]
 [5 6]]


In [35]:
# Arithmetic in numpy

In [39]:
# 1. Scalar Arithmetic
import numpy as np
array = np.array([1,2,3])
print(array +1) # adding 1 to each element
print(array -2) # subtracting 2 from each element
print(array *3) # multiplying each element by 3
print(array /4) # dividing each element by 4
print(array **5) # to the power of 5 of each element

[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[  1  32 243]


In [47]:
# 2. Vectorized Math Functions
array = np.array([1.01, 2.5 ,3.99])
print(np.sqrt(array))
print(np.round(array))
print(np.floor(array))
print(np.ceil(array))
print(np.pi)
# EXERCISE
radii = np.array([1,2,3])
print(np.pi*(radii**2))

[1.00498756 1.58113883 1.99749844]
[1. 2. 4.]
[1. 2. 3.]
[2. 3. 4.]
3.141592653589793
[ 3.14159265 12.56637061 28.27433388]


In [49]:
# 3. Element wise Arithmetic
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [53]:
# 4. Comparison Operators
scores = np.array([91,55,100,73,82,64])
print(scores==100)
print(scores>=60)
print(scores<60)
scores[scores <60]=0
print(scores)

[False False  True False False False]
[ True False  True  True  True  True]
[False  True False False False False]
[ 91   0 100  73  82  64]


In [54]:
# Broadcasting

In [58]:
array1 = np.array([[1,2,3,4]])
array2 = np.array([[1],
                   [2],
                   [3],
                   [4]])
print(array1.shape)
print(array2.shape)
print(array1 * array2) #vitually expanding the dimensions of our arrays
array3 = np.array([[1,2,3,4],
                   [5,6,7,8]])
print(array2.shape)
print(array3.shape)
print(array2 * array3) # impossible as there is not a dimension of 1 in array3 and neither does it match with array2 in any way

(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]
(4, 1)
(2, 4)


ValueError: operands could not be broadcast together with shapes (4,1) (2,4) 

In [59]:
# Aggregate Functions

In [63]:
array = np.array([[1,2,3,4,5],
                  [6,7,8,9,10]])
print(np.sum(array)) # returns the sum of elements
print(np.mean(array)) # returns the mean of elements
print(np.std(array)) # returns the standard deviation of elements
print(np.var(array)) # returns the variance
print(np.min(array)) # returns the min
print(np.max(array)) # returns the max
print(np.argmin(array)) # returns the position of the minimum number
print(np.argmax(array)) # returns the position of the maximum element
# Sum of all columns
print(np.sum(array, axis=0))
# Sum of all rows
print(np.sum(array, axis=1))

55
5.5
2.8722813232690143
8.25
1
10
0
9
[ 7  9 11 13 15]
[15 40]


In [64]:
# Filtering

In [77]:
ages = np.array([[21, 17, 19, 20, 16, 30, 18, 65],
                 [39, 22, 15, 99, 18, 19, 20, 21]])
teenagers= ages[ages < 18]
print(teenagers)
adults = ages[(ages >=18) & (ages <65)]
print(ages[(ages < 18) | (ages >= 65)])
print(adults)
print(ages[(ages>=65)])
print(ages[ages % 2==0])
print(ages[ages % 2!=0])
adults1= np.where(ages>=18, ages, 0)
print(adults1)

[17 16 15]
[17 16 65 15 99]
[21 19 20 30 18 39 22 18 19 20 21]
[65 99]
[20 16 30 18 22 18 20]
[21 17 19 65 39 15 99 19 21]
[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]


In [78]:
# Random Numbers

In [105]:
import numpy as np
rng= np.random.default_rng() # This generates random numbers
print(rng.integers(1, 7))
print(rng.integers(low =1, high=101))
print(rng.integers(low =1, high=101, size=3)) # 1D array with 1 row and 3 columns
print(rng.integers(low =1, high=101, size=(3,3))) # 2D array with 3 rows and 3 columns
rng= np.random.default_rng(seed=1)
print(rng.integers(low =1, high=101, size=(3,3))) #a seed is used to initialize the random number generator so that the sequence of random numbers is repeatable.
print(np.random.uniform()) #the uniform() method is part of the random module and it is used to generate a random floating-point number between two given values.
print(np.random.uniform(low=-1, high=1))
print(np.random.uniform(low=1, high=101, size=(3,2)))
np.random.seed(seed=1)
print(np.random.uniform(low=1, high=101, size=(3,2)))
# Shuffling an array
rng = np.random.default_rng()
array =np.array([1,2,3,4,5])
print(array)
rng.shuffle(array)
print(array)
fruits = np.array(["🍎","orange","banana","coconut","pineapple"])
print(fruits)
print(rng.choice(fruits, size=(3,3)))
rng.shuffle(fruits)
print(fruits)

6
3
[40 68 80]
[[100  52  87]
 [ 65  60  52]
 [ 72  68  53]]
[[48 52 76]
 [96  4 15]
 [83 95 25]]
0.1862602113776709
-0.3088785459139045
[[40.67674742 54.8816734 ]
 [42.91945144 69.52195004]
 [21.44522497 88.81174364]]
[[42.70220047 73.03244934]
 [ 1.01143748 31.23325726]
 [15.67558908 10.23385948]]
[1 2 3 4 5]
[4 5 2 1 3]
['🍎' 'orange' 'banana' 'coconut' 'pineapple']
[['🍎' 'orange' '🍎']
 ['pineapple' 'orange' 'banana']
 ['orange' '🍎' '🍎']]
['🍎' 'pineapple' 'coconut' 'orange' 'banana']
